drop table if exists exam cascade;

create table exam (
    id bigint generated by default as identity,
    nickname varchar(30),
    start_date varchar(50),
    end_date varchar(50),
    exam_name varchar(255),
    subject varchar(50),
    primary key (id)
);