drop table if exists exam cascade;

create table exam (
    id bigint generated by default as identity,
    exam_id varchar(36),
    nickname varchar(30),
    start_date varchar(50),
    end_date varchar(50),
    exam_name varchar(255),
    default_exam boolean,
    primary key (id)
);