drop table if exists folder cascade;

create table folder (
    id bigint generated by default as identity,
    nickname varchar(30),
    folder_id bigint,
    folder_name varchar(50),
    primary key (id)
);