drop table if exists member cascade;

create table member (
  id bigint generated by default as identity,
  nickname varchar(30),
  email varchar(50),
  password varchar(30),
  suryong varchar(10),
  primary key (id)
);