drop table if exists note cascade;

create table note (
    id bigint generated by default as identity,
    folder_id varchar(36),
    note_id varchar(36),
    title varchar(50),
    content varchar(10000),
    primary key (id)
);