drop table if exists note cascade;

create table note (
    id bigint generated by default as identity,
    folder_id bigint,
    note_id bigint,
    title varchar(50),
    content varchar(3000),
    primary key (id)
);