drop table if exists plan cascade;

create table plan (
    id bigint generated by default as identity,
    subject_id varchar(36),
    week varchar(50),
    content varchar(255),
    date DATE,
    learned boolean,
    primary key (id)
);