drop table if exists plan cascade;

create table plan (
    id bigint generated by default as identity,
    exam_id bigint,
    week varchar(50),
    content varchar(255),
    date varchar(50),
    learned boolean,
    FOREIGN KEY (exam_id) REFERENCES exam(id),
    primary key (id)
);