drop table if exists style cascade;

create table style (
  id bigint generated by default as identity,
  nickname varchar(30),
  study_time int,
  study_subject int,
  study_style varchar(30),
  primary key (id)
);