drop table if exists subject cascade;

create table subject (
    id bigint generated by default as identity,
    exam_id varchar(36),
    subject_id varchar(36),
    subject varchar(50),
    primary key (id)
);
