drop table if exists timer cascade;

create table timer (
    id bigint generated by default as identity,
    subject_id varchar(36) NOT NULL,
    date DATE NOT NULL,
    start_time varchar(8),
    end_time varchar(8),
    primary key (id)
);