drop table if exists total_time cascade;

create table total_time (
    id bigint generated by default as identity,
    subject_id varchar(36) NOT NULL,
    date DATE NOT NULL,
    total varchar(8),
    primary key (id)
);